# CMake generated Testfile for 
# Source directory: C:/Users/aluja/Desktop/DL/tests
# Build directory: C:/Users/aluja/Desktop/DL/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(tensor_tests "C:/Users/aluja/Desktop/DL/tests/Debug/tensor_tests.exe")
  set_tests_properties(tensor_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;24;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(tensor_tests "C:/Users/aluja/Desktop/DL/tests/Release/tensor_tests.exe")
  set_tests_properties(tensor_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;24;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(tensor_tests "C:/Users/aluja/Desktop/DL/tests/MinSizeRel/tensor_tests.exe")
  set_tests_properties(tensor_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;24;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(tensor_tests "C:/Users/aluja/Desktop/DL/tests/RelWithDebInfo/tensor_tests.exe")
  set_tests_properties(tensor_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;24;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
else()
  add_test(tensor_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ops_tests "C:/Users/aluja/Desktop/DL/tests/Debug/ops_tests.exe")
  set_tests_properties(ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;25;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ops_tests "C:/Users/aluja/Desktop/DL/tests/Release/ops_tests.exe")
  set_tests_properties(ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;25;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ops_tests "C:/Users/aluja/Desktop/DL/tests/MinSizeRel/ops_tests.exe")
  set_tests_properties(ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;25;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ops_tests "C:/Users/aluja/Desktop/DL/tests/RelWithDebInfo/ops_tests.exe")
  set_tests_properties(ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;25;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
else()
  add_test(ops_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(matrix_ops_tests "C:/Users/aluja/Desktop/DL/tests/Debug/matrix_ops_tests.exe")
  set_tests_properties(matrix_ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;26;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(matrix_ops_tests "C:/Users/aluja/Desktop/DL/tests/Release/matrix_ops_tests.exe")
  set_tests_properties(matrix_ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;26;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(matrix_ops_tests "C:/Users/aluja/Desktop/DL/tests/MinSizeRel/matrix_ops_tests.exe")
  set_tests_properties(matrix_ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;26;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(matrix_ops_tests "C:/Users/aluja/Desktop/DL/tests/RelWithDebInfo/matrix_ops_tests.exe")
  set_tests_properties(matrix_ops_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;26;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
else()
  add_test(matrix_ops_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(linear_tests "C:/Users/aluja/Desktop/DL/tests/Debug/linear_tests.exe")
  set_tests_properties(linear_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;27;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(linear_tests "C:/Users/aluja/Desktop/DL/tests/Release/linear_tests.exe")
  set_tests_properties(linear_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;27;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(linear_tests "C:/Users/aluja/Desktop/DL/tests/MinSizeRel/linear_tests.exe")
  set_tests_properties(linear_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;27;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(linear_tests "C:/Users/aluja/Desktop/DL/tests/RelWithDebInfo/linear_tests.exe")
  set_tests_properties(linear_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;27;add_test;C:/Users/aluja/Desktop/DL/tests/CMakeLists.txt;0;")
else()
  add_test(linear_tests NOT_AVAILABLE)
endif()
